# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myprogramm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
import sys, os
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox, QTableView 
from style import *

class form(QMainWindow):
    def __init__(self):
        os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
        super().__init__()
        self.style = Ui_MainWindow()
        self.style.setupUi(self)
        self.model = QtSql.QSqlTableModel()
        self.model.setTable('field')
        self.model.setEditStrategy(QtSql.QSqlTableModel.OnFieldChange)
        self.model.select()
        self.model.setHeaderData(0, QtCore.Qt.Horizontal,"ID")
        self.model.setHeaderData(1, QtCore.Qt.Horizontal,"Дата")
        self.show()
    
if __name__ == '__main__':
    app = QApplication(sys.argv)
    frm = form()
    sys.exit(app.exec_())